### PR TITLE
Adding qtgraphicaleffects into qt-modules.txt

### PR DESCRIPTION
**Pull request by rahuldevikar761**
Adding qtgraphicaleffects into qt-modules.txt worked for me.

### CODE REVIEW

**Comment by synapticvoid** [comment]
Hi @rahuldevikar761 ,

I don't see any file change in your PR, can you please update it so I can review the content?

**Comment by rahuldevikar761** [comment]
I have updated the qt-moodules.txt with qtgraphicaleffects.

I updated the module and ran the init-qtrpi-full.sh script and worked for me.

**Comment by synapticvoid** [comment]
I think you forgot to include your commit in the PR (the PR states that you didn't change any file), are you talking about this one https://github.com/rahuldevikar761/qtrpi/commit/5578d836193df4c2d4a2ac68a98948b9b4d4817b ?

If so, please update the PR so I can properly review it.

**Comment by rahuldevikar761** [comment]
Yes.

**Comment by synapticvoid** [comment]
I think you have to recreate a PR with this commit so I can properly merge it.

Please submit this new PR to be merged to the `develop` branch.

**Comment by rahuldevikar761** [comment]
Did that worked?

**Comment by GuillaumeLazar** [comment]
The PR is empty, I close it.

**Pull request closed without merging**
